# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mockupRegistrarPatente.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import res_rc

class RegistroPatentes(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1098, 828)
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/background/icon_goldenAi.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(39, 39, 991, 721))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(80, 40, 471, 661))
        self.label.setStyleSheet("border-image: url(:/image/background/background_register_plate.jpg);\n"
"background-color: rgba(0, 0, 0, 0.8);\n"
"border-top-left-radius: 50px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(494, 35, 431, 671))
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_2.setStyleSheet("background-color:rgba(255,255,255,255);\n"
"border-bottom-right-radius: 50px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(580, 140, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.Patente = QtWidgets.QPlainTextEdit(self.widget)
        self.Patente.setGeometry(QtCore.QRect(510, 220, 281, 31))
        self.Patente.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.Patente.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border: none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"")
        self.Patente.setObjectName("Patente")
        self.bAgregar = QtWidgets.QPushButton(self.widget)
        self.bAgregar.setGeometry(QtCore.QRect(820, 210, 40, 40))
        font = QtGui.QFont()
        self.bAgregar.setFont(font)
        self.bAgregar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bAgregar.setStyleSheet(" QPushButton {\n"
"    background-color: transparent; \n"
"     border: none;\n"
"}\n"
"QPushButton:hover {\n"
"      background-color: green;\n"
"}")
        self.bAgregar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/image/background/lista-de-verificacion.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bAgregar.setIcon(icon1)
        self.bAgregar.setIconSize(QtCore.QSize(40, 40))
        self.bAgregar.setObjectName("bAgregar")
        self.bEliminar = QtWidgets.QPushButton(self.widget)
        self.bEliminar.setGeometry(QtCore.QRect(860, 210, 40, 40))
        font = QtGui.QFont()
        self.bEliminar.setFont(font)
        self.bEliminar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bEliminar.setStyleSheet(" QPushButton {\n"
"    background-color: transparent; \n"
"     border: none;\n"
"}\n"
"QPushButton:hover {\n"
"      background-color: #B22222;\n"
"}")
        self.bEliminar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/image/background/eliminar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bEliminar.setIcon(icon2)
        self.bEliminar.setIconSize(QtCore.QSize(40, 40))
        self.bEliminar.setObjectName("bEliminar")
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        self.scrollArea.setGeometry(QtCore.QRect(510, 270, 381, 391))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 379, 389))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.MostrarPatentes = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.MostrarPatentes.setGeometry(QtCore.QRect(0, 0, 381, 391))
        self.MostrarPatentes.setStyleSheet("background-color:white;")
        self.MostrarPatentes.setText("")
        self.MostrarPatentes.setObjectName("MostrarPatentes")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.bAtras = QtWidgets.QPushButton(self.widget)
        self.bAtras.setGeometry(QtCore.QRect(510, 60, 40, 41))
        self.bAtras.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bAtras.setStyleSheet("QPushButton {\n"
"     background-color: transparent; \n"
"      border: none;\n"
" }\n"
" QPushButton:hover {\n"
"      background-color: grey;\n"
" }")
        self.bAtras.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/image/background/hacia-atras.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bAtras.setIcon(icon3)
        self.bAtras.setIconSize(QtCore.QSize(40, 40))
        self.bAtras.setObjectName("bAtras")
        self.bAtras.clicked.connect(lambda: self.openGoldenAi(MainWindow))
        self.bSalir = QtWidgets.QPushButton(self.widget)
        self.bSalir.setGeometry(QtCore.QRect(840, 60, 51, 51))
        self.bSalir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bSalir.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"     background-color: transparent; \n"
"      border: none;\n"
" }\n"
" QPushButton:hover {\n"
"      background-color: grey;\n"
" }")
        self.bSalir.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/image/background/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bSalir.setIcon(icon4)
        self.bSalir.setObjectName("bSalir")
        self.bSalir.clicked.connect(MainWindow.close)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ingresar"))
        self.label_3.setText(_translate("MainWindow", "Register Plate"))
        self.Patente.setPlaceholderText(_translate("MainWindow", "Ingrese su patente"))

    def openGoldenAi(self, MainWindow):
        from GoldenAi import GoldenAi
        MainWindow.hide()
        self.goldenAiWindow = QtWidgets.QMainWindow()
        self.goldenAi = GoldenAi()
        self.goldenAi.setupUi(self.goldenAiWindow)
        self.goldenAiWindow.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = RegistroPatentes()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
